### ISSUE TITLE
Nim's exception mechanism broken

### ISSUE THREAD

**Issue by panno8M** [godot-nim/gdextshell#28]
## Reproduction

```nim
method ready* (self: MyClass) {.gdsync.} =
  raise newException(CatchableError, "test error")
```

## Expected Result

```console
Error: unhandled exception: test error [CatchableError]
```

## Current Result

No output and freeze.

related to #25

**Comment by insomniacUNDERSCORElemon** [comment]
It does seem to work with try except, though.

`import strutils`

`const  break_string:string = "123456789012345678901"`


```
try: 
  if break_string.parseInt == 0: echo "hmm"
except ValueError:
  echo "bwaaaah"
```

That is, if you know the exact error that can happen.
